# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl }:

self: super: {
  "openevolve" = super.buildPythonPackage rec {
    pname = "openevolve";
    version = "0.2.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/8a/9ad5b05ff90384ab5090e235bd7af78a4c160cfcc00b74d4f4d2e9196afe/openevolve-0.2.11-py3-none-any.whl";
      sha256 = "1j9a0j3j0ljgzva2cc9pr9k27a2lgcfn7m49scdq76kja6k9ligp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      pkgs.python3Packages.flask
      pkgs.python3Packages.numpy
      pkgs.python3Packages.openai
      pkgs.python3Packages.pyyaml
      pkgs.python3Packages.tqdm
    ];
  };
 }
