name: openevolve-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - openai
  - pyyaml
  - numpy
  - tqdm
  - flask
  - scipy
  - deap
  - nltk
  - dacite
  - evaluate
  - matplotlib
  - debugpy
  - litellm[proxy]